FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# credcard_user

Credicard user é uma API simples para consulta de dados de cartão de créditos para testes.

## Credcard users Collection [/credcarduser]

### List All Credcard_user [GET]

+ Response 200 (application/json)

            {
                "credcard_user": "Favourite programming language?",
                [
                      {
                        "nomePortador": "Ashlee Dickson",
                        "numeroCartao": 5210904613474491,
                        "anoVencimento": 2017,
                        "mesVencimento": 8,
                        "bandeira": "MasterCard",
                        "cvv": 211,
                        "valorTransacao": "1280,00"
                      },
                      {
                        "nomePortador": "Houston Haynes",
                        "numeroCartao": 5353716778564305,
                        "anoVencimento": 2017,
                        "mesVencimento": 8,
                        "bandeira": "MasterCard",
                        "cvv": 224,
                        "valorTransacao": "280,00"
                      },
                      {
                        "nomePortador": "Houston Haynes",
                        "numeroCartao": 5353716778564305,
                        "anoVencimento": 2017,
                        "mesVencimento": 8,
                        "bandeira": "MasterCard",
                        "cvv": 224,
                        "valorTransacao": "280,00"
                      },
                      {
                        "nomePortador": "Gayle Marquez",
                        "numeroCartao": 5364608526975544,
                        "anoVencimento": 2018,
                        "mesVencimento": 7,
                        "bandeira": "MasterCard",
                        "cvv": 255,
                        "valorTransacao": "5580,00"
                      },
                      {
                        "nomePortador": "Estes Grimes",
                        "numeroCartao": 5345600628658197,
                        "anoVencimento": 2018,
                        "mesVencimento": 7,
                        "bandeira": "MasterCard",
                        "cvv": 565,
                        "valorTransacao": "3790,00"
                      },
                      {
                        "nomePortador": "Violet Guthrie",
                        "numeroCartao": 5513911491840150,
                        "anoVencimento": 2018,
                        "mesVencimento": 6,
                        "bandeira": "MasterCard",
                        "cvv": 240,
                        "valorTransacao": "880,00"
                      },
                      {
                        "nomePortador": "Delacruz Franks",
                        "numeroCartao": 4929457311629085,
                        "anoVencimento": 2018,
                        "mesVencimento": 10,
                        "bandeira": "Visa",
                        "cvv": 650,
                        "valorTransacao": "135,90"
                      },
                      {
                        "nomePortador": "Dickerson Carlson",
                        "numeroCartao": 4532381094425710,
                        "anoVencimento": 2017,
                        "mesVencimento": 8,
                        "bandeira": "Visa",
                        "cvv": 257,
                        "valorTransacao": "513,90"
                      },
                      {
                        "nomePortador": "Garrison Dale",
                        "numeroCartao": 4024007179959779,
                        "anoVencimento": 2018,
                        "mesVencimento": 1,
                        "bandeira": "Visa",
                        "cvv": 550,
                        "valorTransacao": "1890,90"
                      },
                      {
                        "nomePortador": "Leann Pace",
                        "numeroCartao": 4716530088563591,
                        "anoVencimento": 2017,
                        "mesVencimento": 8,
                        "bandeira": "Visa",
                        "cvv": 947,
                        "valorTransacao": "212,10"
                      },
                      {
                        "nomePortador": "Ladonna Gamble",
                        "numeroCartao": 4532029571083441,
                        "anoVencimento": 2018,
                        "mesVencimento": 4,
                        "bandeira": "Visa",
                        "cvv": 992,
                        "valorTransacao": "8101,00"
                      },
                      {
                        "nomePortador": "Stevens Vargas",
                        "numeroCartao": 4532931086489668,
                        "anoVencimento": 2017,
                        "mesVencimento": 3,
                        "bandeira": "Visa",
                        "cvv": 169,
                        "valorTransacao": "1822,00"
                      },
                      {
                        "nomePortador": "Manning Montgomery",
                        "numeroCartao": 4716733660949309,
                        "anoVencimento": 2018,
                        "mesVencimento": 2,
                        "bandeira": "Visa",
                        "cvv": 154,
                        "valorTransacao": "5115,70"
                      },
                      {
                        "nomePortador": "Macdonald Bell",
                        "numeroCartao": 4916277803042943,
                        "anoVencimento": 2017,
                        "mesVencimento": 8,
                        "bandeira": "Visa",
                        "cvv": 585,
                        "valorTransacao": "1202,60"
                      },
                      {
                        "nomePortador": "Ashlee Dickson",
                        "numeroCartao": 4539576060301851,
                        "anoVencimento": 2017,
                        "mesVencimento": 7,
                        "bandeira": "Visa",
                        "cvv": 762,
                        "valorTransacao": "2016,00"
                      }
                    ]
            }